### ISSUE TITLE
Ablation study

### ISSUE THREAD

**Issue by 1372746244** [sunny2109/SAFMN#16]
Hello, I would like to ask a question:
      How is the inverted residual block module defined in ablation experiments? Because I remember that in MobileNet v2, this module has a very small number of parameters.But I saw that in your article's ablation experiment, replacing CCM with inverted residual block significantly increased the parameter quantity.
      I would greatly appreciate it if you could help clarify my confusion. Thank you!

**Comment by sunny2109** [comment]
Hi, sorry for the late reply.
In our ablation experiments, replacing the CCM with the IRB increases the number of parameters of the model from **239.52k** to **245.28k**, and it seems to me that they are almost the same scale of size. The increase in parameter size is mainly due to performing depthwise convolution in the expanded feature dimensions.

**Comment by 1372746244** [comment]
Thanks for your answer！
